# Generated by Django 4.2.6 on 2023-10-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmoney',
            old_name='tha_amount',
            new_name='the_amount',
        ),
    ]
