# Generated by Django 4.2.6 on 2023-10-27 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankApp', '0002_rename_tha_amount_sendmoney_the_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmoney',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='the_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
