# Generated by Django 4.2.6 on 2023-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0006_remove_loanrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='date_requested',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AcceptedLoan',
        ),
    ]
