# Generated by Django 4.1 on 2023-11-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0008_acceptedloan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptedLoan',
        ),
    ]
